export type HeritageItem = {
    id?: string;
    name: string;
    type: string;
    origin?: string;
    yearOfRecognition?: string;
    province: string;
    municipality: string;
    latitude: string;
    longitude: string;
    description: string;
    culturalSignificance: string;
    preservationStatus: string;
    imageUrl: string;
    createdBy?: string;
    createdAt?: any;
    custodianId?: string;
    festivalIds?: string[];
    relatedHeritageIds?: string[];
};